// src/components/svelte/app.svelte
<script>
  import '../../assets/orbit.min.css';
  import { onMount } from 'svelte';
    onMount(async () => {
    await import('../../assets/orbit.mjs');
  });
  let msg = 'Svelte';
</script>

<style lang="css">
  .satellite {
    background: var(--o-cyan-light) !important;
    border: none !important;
  }
  o-arc {
    --o-fill: var(--o-cyan-light)  !important;
  }
  .bigbang {
    height: 300px;
  }
  .gravity-spot {
    --o-force: 600px
  }
</style>
    
<div class="bigbang not-content">
  <div class="gravity-spot">
    <div class="orbit">
      <div class="satellite grow-1x at-center">{msg}</div>
    </div>
    <div class="orbit-2 range-180 from-180">
      <o-arc shape="circle" class="shrink-50"></o-arc>
    </div>
    <div class="orbit-3 range-270 ">
      <o-arc shape="circle" class="shrink-50"></o-arc>
    </div>
  </div>
</div>

// src/components/react/app.jsx
import orbit from '../../assets/orbit.min.js?url'
import  '../../assets/orbit.min.css'


export default function MyApp() {
return (
   <div>
     <style>{`.bigbang { height: 300px; } `}</style>
    <div className="bigbang not-content" >
    <div className="gravity-spot">
      <div className="orbit-4 range-90 fit-range">
        <div className="satellite">1</div>
        <div className="satellite"></div>
        <div className="satellite">2</div>
        <div className="satellite"></div>
        <div className="satellite">3</div>
      </div>
      <div className="orbit-5">
        <o-progress shape="zigzag" value="90"></o-progress>
      </div>
      <div className="orbit-6">
        <o-arc>lapalapa</o-arc>
        <o-arc>lapalapa</o-arc>
        <o-arc>lapalapa</o-arc>
        <o-arc>lapalapa</o-arc>
      </div>
    </div>
    
  </div>
  <script src={orbit}></script>
   </div>
    
  

    )
    
}
